config/routes.rb
AprendoSolo::Application.routes.draw do 
  match "examination/all", :to => "examination#all", :as => :topic_indexx

  get "examination/new"

  get "examination/show"

  get "examination/calification"

  resources :users, :shallow => true do 
   
       get "users/:id", :to => "users#show", :as => :user
       get "users/:id/edit"         

   end 
  resources :courses, :shallow => true do
    resources :video_loaders  
      get "video_loaders/:id", :to => "video_loaders#show", :as => :video_loader   
      

  end
  
  resources :topics do
    resources :quests
  end
  resources :quests do
    resources :answers
  end
   match "topic/:id/quest_user", :to => "quests#user_quest", :as => :quests
   match "users/:id/videos",:to =>"users#videos", :as => :users_videos
   match "/auth/:provider/callback" => "sessions#create"
   match "/signout" => "sessions#destroy", :as => :signout
   match "/auth/:provider/callback" => "sessions#create"
   match "home/members",:to => "home#members", :as => :members
   match "video_loaders/", :to => "video_loaders#index", :as => :video_loaders
   get "home/index"

   get "home/courses"

   get "home/terms"

   get "home/tutorial"

   get "home/about_us"
  
   get "/courses/:id/video", :to => "courses#video_loaders", :as => :video
   match '/courses/:id/new_video', :to => "courses#new_video", :as => :new_video_course
   
  

   root :to => 'home#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :quests
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
    @quest = @topic.quests

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_indexx_path, notice: 'Topic was successfully created.' }
        format.json { render json: topic_indexx_path, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :descritption %><br />
    <%= f.text_area :descritption %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Descritption</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= topic.descritption %></td>
    <td><%= topic.value %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<div class="container content natural-margin" >
  <div class="span10" style="position: fixed; background: #eff4f8; margin-left: 0px!important;margin-top: -10px; border-bottom: solid 1px #b6ced7;">
      <div class="span2" style="width: 250px; height: 90px;">
        <p id="notice"><%= notice %></p>
        <p>
          <b>Title:</b>
          <%= @topic.title %>
        </p>
        <p>
          <b>Descritption:</b>
          <%= @topic.descritption %>
        </p>
        <p>
          <b>Value:</b>
          <%= @topic.value %>
        </p>
        <%= link_to 'Edit', edit_topic_path(@topic) %> |
        <%= link_to 'Back', topics_path %>
      </div>
        <div id="result_msg" style="float: right;"></div>
      <div style="float: left;">
          <%= render :partial =>  "examination/form_quest"%>
      </div>
  </div>

  <div id="quest_elements" class="span10" style="margin: 140px 0px 50px 0px">
    <% @quest.each do |quest| %>
        <div class="quest-element">
            <b><%=  quest.description%></b>
            <a href="#" onclick="return false" class="btn quest-btn">Responder</a>

              <div style="float: left;">
                <%= render :partial =>  "examination/form_answer",
                           :locals => {:quest => quest, :text_2 => t(:'text_2')} %>
              </div>
            </br>

        </div>
    <% end %>
</div>
</div>