config/routes.rb
AprendoSolo::Application.routes.draw do 
  match "examination/all", :to => "examination#all", :as => :topic_indexx

  get "examination/new"

  get "examination/show"

  get "examination/calification"

  resources :users, :shallow => true do 
   
       get "users/:id", :to => "users#show", :as => :user
       get "users/:id/edit"         

   end 
  resources :courses, :shallow => true do
    resources :video_loaders  
      get "video_loaders/:id", :to => "video_loaders#show", :as => :video_loader   
      

  end
  
  resources :topics do
    resources :quests
  end
  resources :quests do
    resources :answers
  end
   match "topic/:id/quest_user", :to => "quests#user_quest", :as => :quests
   match "users/:id/videos",:to =>"users#videos", :as => :users_videos
   match "/auth/:provider/callback" => "sessions#create"
   match "/signout" => "sessions#destroy", :as => :signout
   match "/auth/:provider/callback" => "sessions#create"
   match "home/members",:to => "home#members", :as => :members
   match "video_loaders/", :to => "video_loaders#index", :as => :video_loaders
   get "home/index"

   get "home/courses"

   get "home/terms"

   get "home/tutorial"

   get "home/about_us"
  
   get "/courses/:id/video", :to => "courses#video_loaders", :as => :video
   match '/courses/:id/new_video', :to => "courses#new_video", :as => :new_video_course
   
  

   root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  #Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
      #   :recoverable, :rememberable, :trackable, :validatable
  has_many :courses
  has_many :video_loaders
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :about_me, :avatar
  
  mount_uploader :avatar, AvatarUploader
  
  def self.create_with_omniauth(omniauth)

   create! do |user|
       user.provider = omniauth["provider"]
       user.uid = omniauth["uid"]
       user.name = omniauth["info"]["name"]
       user.image = omniauth["info"]["image"]
       user.token = omniauth["credentials"]["token"]
       if user.save        
         #format.html { redirect_to "/auth/:provider/callback", :notice => 'User wass full created' }
       else
        #format.html { redirect_to root_url, :notice => 'User not created' }
       end
       return user
     end
     
    def self.create_from_hash!(hash)
      create(:name => hash['info']['name'])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    find_user
  end
  def show
    find_user
    @users = User.limit(20) 
    
  end
   def new
    @user = User.new(params[:user])
   
    @user=current_user.name
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end
  def edit
     find_user
  end
  
  def videos
    find_user
  end
   
  
  def create
    @user = User.new
    @user.save!
    if @user.save!
      redirect_to @user
    else
      redirect_to root_path
    end
  end
  def update
   find_user
      if @user.update_attributes(params[:user])
        redirect_after_update
      else
        render :edit
      end
  end
  
  def find_user
    @user ||= User.find params[:id]
  end
  def check_edit_permissions!
     raise ActiveRecord::RecordNotFound if current_user == @user
     true
   end
   def redirect_after_update
     if @user != current_user
       redirect_to @user, :notice => t('flash.user_updated') 
     else
       redirect_to @user, :notice => t('flash.user_updated')
     end
   end
   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Editar Usuario</h1>
<div class="span10" style="margin-top:70px;margin-bottom:70px;">
<div class="span3">
<%= form_for(@user) do |f| %>

  <div><%= f.label :email %><br />
  <%= f.email_field :email %></div>
  <%= f.label :Nombre_de_usuario%>
  <%= f.text_field :name%>
  <%= f.label :Acerca_de_mi%>
  <%= f.text_area :about_me, :rows => 7%></br>
  <%= f.label :Imagen_de_usuario%>
  <%= f.file_field :avatar %>
  <div><%= f.submit "Guardar", :class => "btn pull-right"%>  </div>
<% end %>

</div>
</div>

app/views/users/show.html.erb
<div class="content container natural-margin" style="margin-top:39px;">


 <div class="span9" style="margin-top:9px;">
	
   	<div class="span1">
	 <% if @user.avatar? %>
       <div style="background-image:url(<%= @user.avatar%>); width:50px;height:50px;"></div>
     <%else%>
       <div style="background-image:url(<%= @user.image%>); width:50px;height:50px;"></div>
     <%end%>
	<% if current_user.id == @user.id%>
	</br>
	<div class="span5 white">
	  
	  |<%= link_to "editar usuario", edit_user_path%>|
	  <%= link_to "mis videos", users_videos_path%>|

	</div>
	<%end%>
     </div><div class="span7"><h1><%= @user.name%></h1></div>
 </div>

<% if current_user.id == @user.id%>

<div class="span5" style="margin-top:30px;">
	<div class="grey" style="height:50;">
  <%= form_for(@user) do |f| %>
   <% if @user.email?%> 
      Tu email es privado:<%= @user.email %>
   <%else%>
     <div><%= f.label :ingresa_tu_email %><br />
           <%= f.email_field :email %></div>
   <%end%>
   <% if @user.about_me?%>
      
   <%else%>
    <%= f.label :ingresa_tu_descripcción_personal%> 
    <%= f.text_area :about_me, :rows => 7 %></br>

   <%end%>
    <% if current_user.email? & current_user.about_me? == true %>  
    <%else%>      
    <div><%= f.submit "Guardar", :class => "btn pull-right"%>  </div>
   <%end%>
<% end %>
   <h2>Acerca de mí:</h2>
   <div class="ocultable" id="texto1">
	<%= @user.about_me%>
	</div>
	<a href="javascript:MostrarOcultar('texto1');" id="enlace1"> Mostrar/Ocultar</a>
	</div>
   	<div class="grey" style="height:350px; margin-bottom:50px;">
	  <h2>Red de usuarios:</h2>
	    <% @users.each do |user|%>
	     <div style="width:60px; height:60px; float:left;">
	        <a rel="tooltip" data-placement="top" title="<%= user.about_me %>">
	          <% if user.avatar? %>
	
	           <div class="squere" id="<%= user.id %>" style="background-image:url(<%=user.avatar%>)" onClick="goToProfile('<%= user_path(user.id)%>')"></div>
	
	          <%else%>
	           <div class="squere" id="<%= user.id %>" style="background-image:url(<%=user.image%>)" onClick="goToProfile('<%= user_path(user.id)%>')"></div>
	          <%end%>
	        </a>
	     </div>
	   <%end%><div class="pull-right"></br></br></br>
	  <%= link_to "Members", members_path%></div>
	 </div>
 </div>
<div class="span3 grey content-overflow" style="margin-top:33px; height:300px;">
		<h3> Todos mis cursos:</h3>
 <%@user.courses.each do |courses|%>
   <div class="span2" ><%= link_to courses.title, course_path(courses.id)%>&nbsp;&nbsp;|<%= link_to "editar", edit_course_path(courses.id)%>|</div>
 <%end%>

<%else%>
<div class="span5" style="margin-top:30px;">
	<div class="grey" style="height:50;">
		<h2>Acerca de mí:</h2> <p><%= @user.about_me%></p>		
	</div>
	<div class="grey" style="height:350px; margin-bottom:50px;">
	  <h2>Red de usuarios:</h2>
	    <% @users.each do |user|%>
	     <div style="width:60px; height:60px; float:left;">
	        <a rel="tooltip" data-placement="top" title="<%= user.about_me %>">
	          <% if user.avatar? %>
	         <div class="squere" id="<%= user.id %>" style="background-image:url(<%=user.avatar%>)" onClick="goToProfile('<%= user_path(user.id)%>')"></div>
	          <%else%>
	         <div class="squere" id="<%= user.id %>" style="background-image:url(<%=user.image%>)" onClick="goToProfile('<%= user_path(user.id)%>')"></div>
	          <%end%>
	        </a>
	     </div>
	   <%end%>
	       <div class="pull-right"></br></br></br>
		  <%= link_to "Members", members_path%></div>
	</div>
	 </div>
	
<div class="span3 grey content-overflow" style="margin-top:33px; height:300px;">
	<h3> Todos mis cursos:</h3>
 <%@user.courses.each do |courses|%>
   <div class="span2" ><%= link_to courses.title, course_path(courses.id)%></div>
 <%end%>
</div>
<%end%>
 
</div>
</div>
</div>
</div>

<script type="text/javascript">

	function goToProfile(url){
		console.log('hola');
		window.location = url;
		
	}

</script>

app/views/users/videos.html.erb
<h3>User Videos</h3>
<div class="span10" style="margin-top:50px;">
 <%= current_user.video_loaders.each do |user_videos|%>
 <%end%>
</div>