config/routes.rb
AprendoSolo::Application.routes.draw do 
  match "examination/all", :to => "examination#all", :as => :topic_indexx

  get "examination/new"

  get "examination/show"

  get "examination/calification"

  resources :users, :shallow => true do 
   
       get "users/:id", :to => "users#show", :as => :user
       get "users/:id/edit"         

   end 
  resources :courses, :shallow => true do
    resources :video_loaders  
      get "video_loaders/:id", :to => "video_loaders#show", :as => :video_loader   
      

  end
  
  resources :topics do
    resources :quests
  end
  resources :quests do
    resources :answers
  end
   match "topic/:id/quest_user", :to => "quests#user_quest", :as => :quests
   match "users/:id/videos",:to =>"users#videos", :as => :users_videos
   match "/auth/:provider/callback" => "sessions#create"
   match "/signout" => "sessions#destroy", :as => :signout
   match "/auth/:provider/callback" => "sessions#create"
   match "home/members",:to => "home#members", :as => :members
   match "video_loaders/", :to => "video_loaders#index", :as => :video_loaders
   get "home/index"

   get "home/courses"

   get "home/terms"

   get "home/tutorial"

   get "home/about_us"
  
   get "/courses/:id/video", :to => "courses#video_loaders", :as => :video
   match '/courses/:id/new_video', :to => "courses#new_video", :as => :new_video_course
   
  

   root :to => 'home#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :quest
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  has_many :video_loaders
end

app/models/quest.rb
class Quest < ActiveRecord::Base
  has_many :answers
  belongs_to :topic
end

app/models/responce.rb
class Responce < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :quests
end

app/models/user.rb
class User < ActiveRecord::Base
  #Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
      #   :recoverable, :rememberable, :trackable, :validatable
  has_many :courses
  has_many :video_loaders
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :about_me, :avatar
  
  mount_uploader :avatar, AvatarUploader
  
  def self.create_with_omniauth(omniauth)

   create! do |user|
       user.provider = omniauth["provider"]
       user.uid = omniauth["uid"]
       user.name = omniauth["info"]["name"]
       user.image = omniauth["info"]["image"]
       user.token = omniauth["credentials"]["token"]
       if user.save        
         #format.html { redirect_to "/auth/:provider/callback", :notice => 'User wass full created' }
       else
        #format.html { redirect_to root_url, :notice => 'User not created' }
       end
       return user
     end
     
    def self.create_from_hash!(hash)
      create(:name => hash['info']['name'])
    end
  end
end

app/models/video_loader.rb
class VideoLoader < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  mount_uploader :video_load, VideoLoadUploader
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize, :only => [:index, :about_us]
  def index
   if current_user
     redirect_to current_user
    else
     @video_loaders = VideoLoader.all
     @video_loaders_last = @video_loaders.last
   end
  end

  def courses
  end

  def members
    @users= User.all
  end

  def terms
  end

  def tutorial
  end

  def about_us
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  def create
    @quest = Quest.new(params[:quest])
    respond_to do |format|
      if @quest.save
        format.html { redirect_to(:back, :notice => "Se guardo exitosamente" ) }
        format.js
      else
        format.html { render :action => "No se guardo" }
        format.js
      end
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    find_user
  end
  def show
    find_user
    @users = User.limit(20) 
    
  end
   def new
    @user = User.new(params[:user])
   
    @user=current_user.name
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end
  def edit
     find_user
  end
  
  def videos
    find_user
  end
   
  
  def create
    @user = User.new
    @user.save!
    if @user.save!
      redirect_to @user
    else
      redirect_to root_path
    end
  end
  def update
   find_user
      if @user.update_attributes(params[:user])
        redirect_after_update
      else
        render :edit
      end
  end
  
  def find_user
    @user ||= User.find params[:id]
  end
  def check_edit_permissions!
     raise ActiveRecord::RecordNotFound if current_user == @user
     true
   end
   def redirect_after_update
     if @user != current_user
       redirect_to @user, :notice => t('flash.user_updated') 
     else
       redirect_to @user, :notice => t('flash.user_updated')
     end
   end
   
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/examination_helper.rb
module ExaminationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quests_helper.rb
module QuestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/video_loaders_helper.rb
module VideoLoadersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <title>AprendoSolo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render :partial => "shared/topbar"%>
  
<!--este script permite activar el tooltip de bootstrap-->
<script languaje="Javascript">
<!--
document.write('<style type="text/css">div.ocultable{display: none;}</style>');
function MostrarOcultar(capa,enlace)
{
    if (document.getElementById)
    {
        var aux = document.getElementById(capa).style;
        aux.display = aux.display? "":"block";
    }
}

//-->
</script>
  <script type='text/javascript'>

     $(document).ready(function () {
     if ($("[rel=tooltip]").length) {
     $("[rel=tooltip]").tooltip();
     }
   });
  </script>
<div id="fb-root"></div>
<!--compartir contenido-->
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=336243296469875";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<!--like-->
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=336243296469875";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

</head>
<% if notice%>
    <script>
        setTimeout(function() {
            $(".close").click();
        }, 2500);
    </script>
<div class="alert alert-info" style="margin-top:50px;">
	<button type="button" class="close" data-dismiss="alert">×</button>
  <%= notice %>
</div>
<%end%>
<body class="background whitetext" style ="margin:auto;">
	

<%= yield %>

</body>
</br>
<footer 
style=" 
   position:absolute;
   bottom:0;
   left:0;
   width:100%;
   position: fixed;
     z-index:99;">
<%= render :partial => "shared/footer"%>	
</footer>
</html>

app/views/shared/_footer.html.erb
<div class="row line footer">
	<div class="span12" style="padding-left:100px;">
		<center>
		  ©2012 Aprendo Solo</br>
		  <b>An Idea For</b>
		</center>
	</div>
</div>

app/views/shared/_topbar.html.erb
<div class="container">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav pull-left" ><%= link_to "Aprendo Solo", root_path, :class => "brand"%></ul>
      <ul class="nav pull-right">
	    <% if current_user %>
		    <li class="divider-vertical"></li>
		   <li><%= link_to "Finaliza la sesión ", signout_path %></li>
		   <li class="divider-vertical"></li>
		   <li><div id="friends">
	     <li><%= link_to "Invitar Amigos", "#", :id => "invite_fb_friends"  %></li>

	     <script src="http://connect.facebook.net/en_US/all.js"></script>

	     <script>
	       $(function(){

	         $("a#invite_fb_friends").click(function() {
	           FB.init({ 
	              appId:'336243296469875', 
	              cookie:false, 
	              status:true
	           });

	           FB.ui({ method: 'apprequests', message: ' <%= current_user.name %> Unete la increíble realidad de aprendo solo'});
	         });
	       });
	     </script>
		  </div>

		    
		  <% else %>
		    <li> <%= link_to "Ingresa", "/auth/facebook" %> </li>
		    <li class="divider-vertical"></li>
		  <% end %>
	       
	     
	   
	  </ul>	 
	  
	</div>    
  </div>
</div>
</div>
<div id="fb-root"></div>