config/routes.rb
AprendoSolo::Application.routes.draw do 
  match "examination/all", :to => "examination#all", :as => :topic_indexx

  get "examination/new"

  get "examination/show"

  get "examination/calification"

  resources :users, :shallow => true do 
   
       get "users/:id", :to => "users#show", :as => :user
       get "users/:id/edit"         

   end 
  resources :courses, :shallow => true do
    resources :video_loaders  
      get "video_loaders/:id", :to => "video_loaders#show", :as => :video_loader   
      

  end
  
  resources :topics do
    resources :quests
  end
  resources :quests do
    resources :answers
  end
   match "topic/:id/quest_user", :to => "quests#user_quest", :as => :quests
   match "users/:id/videos",:to =>"users#videos", :as => :users_videos
   match "/auth/:provider/callback" => "sessions#create"
   match "/signout" => "sessions#destroy", :as => :signout
   match "/auth/:provider/callback" => "sessions#create"
   match "home/members",:to => "home#members", :as => :members
   match "video_loaders/", :to => "video_loaders#index", :as => :video_loaders
   get "home/index"

   get "home/courses"

   get "home/terms"

   get "home/tutorial"

   get "home/about_us"
  
   get "/courses/:id/video", :to => "courses#video_loaders", :as => :video
   match '/courses/:id/new_video', :to => "courses#new_video", :as => :new_video_course
   
  

   root :to => 'home#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])
     @video_loaders= VideoLoader.where(:course_id => current_course.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end
  
  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])
   
    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
  def new_video
    @course = Course.find(params[:id])
    @video_loader = VideoLoader.new
    @video_loader.save!
  end
  def video_loaders
    @video_loaders= VideoLoader.where(:course_id => current_course.id)
    @video_loaders_count = @video_loaders.count
  end
 
private
  def current_course
     @course ||= Course.find(params[:id])
  end
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_facebooklike.html.erb
<div class="fb-like" data-href="http://localhost:3000/#{current_course.id}" data-send="true" data-width="450" data-show-faces="true" data-colorscheme="dark" data-font="arial"></div>

app/views/courses/_facebookwall.html.erb
<center>
<div class="fb-comments" data-href="http://localhost:3000/courses/#{current_course.id}" data-num-posts="10" data-width="650" data-colorscheme="dark"></div>
</center>

app/views/courses/_firstvideo.html.erb
<%= @video_loaders.first.title %>
<div id="video-form"></div>
<%= @video_loaders.first.description %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/courses/_videos.html.erb
<div class="span10">
<div class="carousel slide" id="carrouselle">
 <div id="video-course" class="carousel-inner">
<% @video_loaders.each do |video_loader| %>

  <%@id = video_loader.id%>
  <%@title = video_loader.title %>
  <%@description = video_loader.description %>
  <%@video = video_loader.video_load %>
  <% if @id == @video_loaders.first.id %>
       <div class="active item">
	     <center>
	      <h3> <%= @title%> </h3>
	     </center>
	   
  <%else%>
       <div class="item">
	    <center>
	     <h3> <%= @title%> </h3>
	    </center>
  <%end%>
         <div id='<%=@id%>' class="video-course-dimensions">    
	      	<script type="text/javascript" charset="utf-8">
			   jQuery(function($){
			     fv = $("#<%=@id%>").flareVideo();
			     fv.load([
			       {
			         src:  '<%= @video  %>',
			       }
			     ]);
			   })
			 </script>	     
	     </div>
	      <div class="description"><h3>Descripcción:</h3><p> <%=@description%></p> </div>
	      
       </div> 
<%end%>
 
</div>
  <a class="carousel-control left" href="#carrouselle" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#carrouselle" data-slide="next">&rsaquo;</a>
</div>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.title %></td>
    <td><%= course.description %></td>
    <td><%= course.video_loaders%>
	</td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/new_video.html.erb
<%= render :partial => "video_loaders/new"%>

app/views/courses/show.html.erb
<div class="span11" style="margin-top:50px; margin-left:15%;  margin-right:15%; margin-bottom:70px;">
	<%= link_to 'Edit', edit_course_path(@course) %> |
	<%= link_to 'Back', courses_path %>
<p id="notice"><%= notice %></p>
<h1>
  <%= @course.title %>
</h1>
<!-- redirecciona de cursos los videos -->
<%= render "videos"%>
<div class="span9 black", style="margin-left:5%;">
	<p>
	<div class="descript-up">
	  <b>Descripcción:</b>
	  <%= @course.description %></br>
	</p>
	</div>
	<div>
	  <%= render :partial => "facebooklike"%>
	</div>
<!-- redirecciona de cursos los el facebook wall -->
	<%= render "facebookwall"%>
</div> 
</div>

app/views/courses/video_loaders.html.erb
<div class="span16">
<div class="span18">
<%= render :partial => "video_loaders/index"%>
</div>
<div class="span2" style="margin-left:60px; margin-top:90px;">
<center><h1 class="green"><%=  @video_loaders_count %></h1></center>
<center><h2>Videos</h2></center>
</div>
<center>
<div class="btn", style="margin-left:60px; margin-top:35px;">
<%= link_to 'Agregar Video', new_video_course_path %>
</div>
</center>
</div>